name: Publish to npm/yarn on PR to master
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn npm publish --access public
        if: github.event.pull_request.merged == true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
