name: Create Release on PR to master

on:
  pull_request:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Read the version from package.json
      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Create a GitHub Release with the extracted version
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }} # Create the release with version tag
          name: Release v${{ env.VERSION }} # Use `name` instead of `release_name`
          body: |
            Release for pull request #${{ github.event.number }}.
            PR Title: ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure this token has the correct permissions

      # Optional: Push the version tag to the repository
      - name: Push version tag to repository
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
